"""initial-revision

Revision ID: 0b4b1a461488
Revises: 
Create Date: 2026-08-21 20:24:27.756577
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0b4b1a461488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xdeploy_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('stored_name', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('dek_wrapped', sa.String(length=512), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('signer_public_key', sa.String(length=128), nullable=False),
    sa.Column('publisher_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_xdeploy_artifact_project_version')
    )
    op.create_index('ix_xdeploy_artifact_project_created', 'xdeploy_artifacts', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_xdeploy_artifacts_project_id'), 'xdeploy_artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_xdeploy_artifacts_publisher_id'), 'xdeploy_artifacts', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_xdeploy_artifacts_signature'), 'xdeploy_artifacts', ['signature'], unique=False)
    op.create_table('xauth_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_plugin', sa.String(length=100), nullable=True),
    sa.Column('tenant_grantable', sa.Boolean(), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('xauth_tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_xauth_tenant_slug', 'xauth_tenants', ['slug'], unique=False)
    op.create_table('xauth_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_backup_codes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_xauth_user_email', 'xauth_users', ['email'], unique=False)
    op.create_table('xauth_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['xauth_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['xauth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xauth_member_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=True),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['xauth_permissions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['xauth_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['xauth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'permission_id', 'scope_type', 'scope_id', name='uq_member_permission')
    )
    op.create_table('xauth_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['xauth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xauth_notifications_tenant_id'), 'xauth_notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_xauth_notifications_user_id'), 'xauth_notifications', ['user_id'], unique=False)
    op.create_table('xauth_oauth_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('provider_avatar', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_scopes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['xauth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_uid')
    )
    op.create_index('ix_xauth_oauth_user_id', 'xauth_oauth_accounts', ['user_id'], unique=False)
    op.create_table('xauth_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['xauth_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xauth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_jti', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['xauth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xauth_sessions_refresh_token'), 'xauth_sessions', ['refresh_token'], unique=False)
    op.create_table('xauth_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['xauth_users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['xauth_roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['xauth_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('xauth_member_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=True),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['xauth_roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['xauth_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['xauth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'role_id', 'scope_type', 'scope_id', name='uq_member_role')
    )
    op.create_table('xauth_role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['xauth_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['xauth_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('xauth_tenant_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_tenant_status', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['xauth_roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['xauth_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['xauth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_tenant_member')
    )
    op.create_table('market_plugin_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('integration', sa.Text(), nullable=True),
    sa.Column('contributor', sa.JSON(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'version', name='uq_plugin_doc_version')
    )
    op.create_index(op.f('ix_market_plugin_docs_plugin_id'), 'market_plugin_docs', ['plugin_id'], unique=False)
    op.create_table('xdep_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployer_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('repo', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_xdep_deployer_slug_host', 'xdep_deployments', ['deployer_id', 'slug', 'host_id'], unique=False)
    op.create_index(op.f('ix_xdep_deployments_deployer_id'), 'xdep_deployments', ['deployer_id'], unique=False)
    op.create_index(op.f('ix_xdep_deployments_slug'), 'xdep_deployments', ['slug'], unique=False)
    op.create_table('market_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_market_categories_slug'), 'market_categories', ['slug'], unique=True)
    op.create_table('market_developer_webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('developer_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=True),
    sa.Column('events', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_developer_webhooks_developer_id'), 'market_developer_webhooks', ['developer_id'], unique=False)
    op.create_table('market_github_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('github_login', sa.String(length=128), nullable=False),
    sa.Column('github_user_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(length=256), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_github_tokens_user_id'), 'market_github_tokens', ['user_id'], unique=True)
    op.create_table('market_plugins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('developer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homepage', sa.String(length=512), nullable=True),
    sa.Column('repository', sa.String(length=512), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_market_plugins_developer_id'), 'market_plugins', ['developer_id'], unique=False)
    op.create_index(op.f('ix_market_plugins_slug'), 'market_plugins', ['slug'], unique=True)
    op.create_index(op.f('ix_market_plugins_tenant_id'), 'market_plugins', ['tenant_id'], unique=False)
    op.create_table('market_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('developer_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('plugin_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('anomaly_score', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('github_repo', sa.String(length=256), nullable=True),
    sa.Column('github_branch', sa.String(length=255), nullable=True),
    sa.Column('category_ids', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_submissions_developer_id'), 'market_submissions', ['developer_id'], unique=False)
    op.create_table('market_plugin_categories',
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['market_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plugin_id'], ['market_plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plugin_id', 'category_id')
    )
    op.create_table('market_plugin_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['market_plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'user_id', name='uq_rating_plugin_user')
    )
    op.create_index(op.f('ix_market_plugin_ratings_plugin_id'), 'market_plugin_ratings', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_market_plugin_ratings_user_id'), 'market_plugin_ratings', ['user_id'], unique=False)
    op.create_table('market_plugin_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('merkle_root', sa.String(length=128), nullable=True),
    sa.Column('anomaly_score', sa.Integer(), nullable=False),
    sa.Column('is_stable', sa.Boolean(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_yanked', sa.Boolean(), nullable=False),
    sa.Column('yanked_reason', sa.String(length=256), nullable=True),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['market_plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'version', name='uq_plugin_version')
    )
    op.create_index('ix_plugin_version_plugin_id', 'market_plugin_versions', ['plugin_id'], unique=False)
    op.create_table('xsvc_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_xsvc_categories_slug'), 'xsvc_categories', ['slug'], unique=True)
    op.create_table('xsvc_service_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('integration', sa.Text(), nullable=True),
    sa.Column('contributor', sa.JSON(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'version', name='uq_service_doc_version')
    )
    op.create_index(op.f('ix_xsvc_service_docs_service_id'), 'xsvc_service_docs', ['service_id'], unique=False)
    op.create_table('xsvc_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('developer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_class', sa.String(length=256), nullable=True),
    sa.Column('homepage', sa.String(length=512), nullable=True),
    sa.Column('repository', sa.String(length=512), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_xsvc_services_developer_id'), 'xsvc_services', ['developer_id'], unique=False)
    op.create_index(op.f('ix_xsvc_services_slug'), 'xsvc_services', ['slug'], unique=True)
    op.create_index(op.f('ix_xsvc_services_tenant_id'), 'xsvc_services', ['tenant_id'], unique=False)
    op.create_table('xsvc_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('developer_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('service_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('anomaly_score', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('category_ids', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('github_repo', sa.String(length=256), nullable=True),
    sa.Column('github_branch', sa.String(length=128), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xsvc_submissions_developer_id'), 'xsvc_submissions', ['developer_id'], unique=False)
    op.create_table('xsvc_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['xsvc_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'user_id', name='uq_service_rating_user')
    )
    op.create_index('ix_svc_rating_service_id', 'xsvc_ratings', ['service_id'], unique=False)
    op.create_table('xsvc_service_categories',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['xsvc_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['xsvc_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'category_id')
    )
    op.create_table('xsvc_service_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('merkle_root', sa.String(length=128), nullable=True),
    sa.Column('anomaly_score', sa.Integer(), nullable=False),
    sa.Column('is_stable', sa.Boolean(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_yanked', sa.Boolean(), nullable=False),
    sa.Column('yanked_reason', sa.String(length=256), nullable=True),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['xsvc_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'version', name='uq_service_version')
    )
    op.create_index('ix_svc_version_service_id', 'xsvc_service_versions', ['service_id'], unique=False)
    op.create_table('devkeys_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'kind', 'slug', name='uq_devkeys_project_owner_target')
    )
    op.create_index('ix_devkeys_project_owner', 'devkeys_projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_devkeys_projects_owner_id'), 'devkeys_projects', ['owner_id'], unique=False)
    op.create_table('devkeys_signing_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('secret_encrypted', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devkeys_signing_key_user', 'devkeys_signing_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_devkeys_signing_keys_user_id'), 'devkeys_signing_keys', ['user_id'], unique=True)
    op.create_table('devkeys_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('deployment_credential_hash', sa.String(length=64), nullable=True),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['devkeys_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_devkeys_api_key_hash', 'devkeys_api_keys', ['key_hash'], unique=False)
    op.create_index('ix_devkeys_api_key_user', 'devkeys_api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_devkeys_api_keys_project_id'), 'devkeys_api_keys', ['project_id'], unique=False)
    op.create_index(op.f('ix_devkeys_api_keys_user_id'), 'devkeys_api_keys', ['user_id'], unique=False)
    op.create_table('devkeys_project_manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['devkeys_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag', name='uq_devkeys_manifest_project_tag')
    )
    op.create_index('ix_devkeys_manifest_project_created', 'devkeys_project_manifests', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_devkeys_project_manifests_project_id'), 'devkeys_project_manifests', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devkeys_project_manifests_project_id'), table_name='devkeys_project_manifests')
    op.drop_index('ix_devkeys_manifest_project_created', table_name='devkeys_project_manifests')
    op.drop_table('devkeys_project_manifests')
    op.drop_index(op.f('ix_devkeys_api_keys_user_id'), table_name='devkeys_api_keys')
    op.drop_index(op.f('ix_devkeys_api_keys_project_id'), table_name='devkeys_api_keys')
    op.drop_index('ix_devkeys_api_key_user', table_name='devkeys_api_keys')
    op.drop_index('ix_devkeys_api_key_hash', table_name='devkeys_api_keys')
    op.drop_table('devkeys_api_keys')
    op.drop_index(op.f('ix_devkeys_signing_keys_user_id'), table_name='devkeys_signing_keys')
    op.drop_index('ix_devkeys_signing_key_user', table_name='devkeys_signing_keys')
    op.drop_table('devkeys_signing_keys')
    op.drop_index(op.f('ix_devkeys_projects_owner_id'), table_name='devkeys_projects')
    op.drop_index('ix_devkeys_project_owner', table_name='devkeys_projects')
    op.drop_table('devkeys_projects')
    op.drop_index('ix_svc_version_service_id', table_name='xsvc_service_versions')
    op.drop_table('xsvc_service_versions')
    op.drop_table('xsvc_service_categories')
    op.drop_index('ix_svc_rating_service_id', table_name='xsvc_ratings')
    op.drop_table('xsvc_ratings')
    op.drop_index(op.f('ix_xsvc_submissions_developer_id'), table_name='xsvc_submissions')
    op.drop_table('xsvc_submissions')
    op.drop_index(op.f('ix_xsvc_services_tenant_id'), table_name='xsvc_services')
    op.drop_index(op.f('ix_xsvc_services_slug'), table_name='xsvc_services')
    op.drop_index(op.f('ix_xsvc_services_developer_id'), table_name='xsvc_services')
    op.drop_table('xsvc_services')
    op.drop_index(op.f('ix_xsvc_service_docs_service_id'), table_name='xsvc_service_docs')
    op.drop_table('xsvc_service_docs')
    op.drop_index(op.f('ix_xsvc_categories_slug'), table_name='xsvc_categories')
    op.drop_table('xsvc_categories')
    op.drop_index('ix_plugin_version_plugin_id', table_name='market_plugin_versions')
    op.drop_table('market_plugin_versions')
    op.drop_index(op.f('ix_market_plugin_ratings_user_id'), table_name='market_plugin_ratings')
    op.drop_index(op.f('ix_market_plugin_ratings_plugin_id'), table_name='market_plugin_ratings')
    op.drop_table('market_plugin_ratings')
    op.drop_table('market_plugin_categories')
    op.drop_index(op.f('ix_market_submissions_developer_id'), table_name='market_submissions')
    op.drop_table('market_submissions')
    op.drop_index(op.f('ix_market_plugins_tenant_id'), table_name='market_plugins')
    op.drop_index(op.f('ix_market_plugins_slug'), table_name='market_plugins')
    op.drop_index(op.f('ix_market_plugins_developer_id'), table_name='market_plugins')
    op.drop_table('market_plugins')
    op.drop_index(op.f('ix_market_github_tokens_user_id'), table_name='market_github_tokens')
    op.drop_table('market_github_tokens')
    op.drop_index(op.f('ix_market_developer_webhooks_developer_id'), table_name='market_developer_webhooks')
    op.drop_table('market_developer_webhooks')
    op.drop_index(op.f('ix_market_categories_slug'), table_name='market_categories')
    op.drop_table('market_categories')
    op.drop_index(op.f('ix_xdep_deployments_slug'), table_name='xdep_deployments')
    op.drop_index(op.f('ix_xdep_deployments_deployer_id'), table_name='xdep_deployments')
    op.drop_index('ix_xdep_deployer_slug_host', table_name='xdep_deployments')
    op.drop_table('xdep_deployments')
    op.drop_index(op.f('ix_market_plugin_docs_plugin_id'), table_name='market_plugin_docs')
    op.drop_table('market_plugin_docs')
    op.drop_table('xauth_tenant_members')
    op.drop_table('xauth_role_permissions')
    op.drop_table('xauth_member_roles')
    op.drop_table('xauth_invites')
    op.drop_index(op.f('ix_xauth_sessions_refresh_token'), table_name='xauth_sessions')
    op.drop_table('xauth_sessions')
    op.drop_table('xauth_roles')
    op.drop_index('ix_xauth_oauth_user_id', table_name='xauth_oauth_accounts')
    op.drop_table('xauth_oauth_accounts')
    op.drop_index(op.f('ix_xauth_notifications_user_id'), table_name='xauth_notifications')
    op.drop_index(op.f('ix_xauth_notifications_tenant_id'), table_name='xauth_notifications')
    op.drop_table('xauth_notifications')
    op.drop_table('xauth_member_permissions')
    op.drop_table('xauth_audit_logs')
    op.drop_index('ix_xauth_user_email', table_name='xauth_users')
    op.drop_table('xauth_users')
    op.drop_index('ix_xauth_tenant_slug', table_name='xauth_tenants')
    op.drop_table('xauth_tenants')
    op.drop_table('xauth_permissions')
    op.drop_index(op.f('ix_xdeploy_artifacts_signature'), table_name='xdeploy_artifacts')
    op.drop_index(op.f('ix_xdeploy_artifacts_publisher_id'), table_name='xdeploy_artifacts')
    op.drop_index(op.f('ix_xdeploy_artifacts_project_id'), table_name='xdeploy_artifacts')
    op.drop_index('ix_xdeploy_artifact_project_created', table_name='xdeploy_artifacts')
    op.drop_table('xdeploy_artifacts')
    # ### end Alembic commands ###
